<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

eval(base64_decode('JHN0YWZmMSA9IGFycmF5KAoJYXJyYXkoInJhbmsiPT4iYWRtaW4iLCAiZW1haWwiPT4iYWRtaW5AcmF6aWNhbi5jb20iLCAibmljayI9PiJSYXppY2FuIiwgInByb2ciPT4xLCAidHJhbnNsIj0+MSwgImRlc2lnbiI9PjEpLAoJYXJyYXkgKCJyYW5rIj0+ImNvbnRyaWIiLCAiZW1haWwiPT4iTi9BIiwgIm5pY2siPT4ibGVjaGlndWVybyIsICJwcm9nIj0+MSwgInRyYW5zbCI9PjAsICJkZXNpZ24iPT4wKSwKCWFycmF5ICgicmFuayI9PiJjb250cmliIiwgImVtYWlsIj0+ImNkcy1lbW1ldEBob3RtYWlsLmNvbSIsICJuaWNrIj0+IkVtbWV0IiwgInByb2ciPT4wLCAidHJhbnNsIj0+MSwgImRlc2lnbiI9PjApCik7CgpyZXF1aXJlX29uY2UoQVBQUEFUSCAuJy9pbmNsdWRlcy9vdGhlcl92YXJzLnBocCcpOwoKJHN0YWZmID0gYXJyYXlfbWVyZ2UoJHN0YWZmMSwgJHN0YWZmMik7'));


/* End of file vars.php */
/* Location: ./application/includes/vars.php */